### ISSUE TITLE
Does not load "Studio town view" and "Magic town view"

### ISSUE THREAD

**Issue by NER0888** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#7] opened 2020-03-31 10:07 UTC
After patching game, "Studio town view" and "Magic town view" does not load (regardless of chosen resolution and if dgVoodoo2 is checked or not), but areas and buttons are still active and can be used. Other than that, works great. 
My native resolution is 2560x1080. 
I use Sims1WidescreenPatcher.1.2.0.zip. 
I have no idea what other zips (Source code (zip); Source code (tar.gz)) are for.

Please help.  

Magic Town View:

![Magic town view](https://user-images.githubusercontent.com/62935373/78014004-f815a480-734f-11ea-9bef-9b320987948f.jpg)

Studio Town View:

![Studio town view](https://user-images.githubusercontent.com/62935373/78014006-f946d180-734f-11ea-997a-b530b8c11538.jpg)

**Comment by FaithBeam** [comment] 2020-03-31 15:52
@NER0888 

I'll need to look into how to extract UI elements from The Sims because I'm assuming that is what the issue is here. If anyone with more experience in Sims modding can chime in, that'd be great.

**Comment by FaithBeam** [comment] 2020-04-01 19:28
@NER0888 
Sorry for closing this without asking if your issue was fixed. Try this release. https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/v1.2.1/Sims1WidescreenPatcher.1.2.1.zip

**Comment by NER0888** [comment] 2020-04-02 16:54
> 
> 
> @NER0888
> Sorry for closing this without asking if your issue was fixed. Try this release. https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/v1.2.1/Sims1WidescreenPatcher.1.2.1.zip
> 
> https://i.imgur.com/mv26wiD.png

Hi, still have an issue here: 
2020-04-02 19:52:17,992 [1] ERROR HexEditApp.MainWindow - An unhandled exception occurred: Access to the path 'C:\Program Files (x86)\Maxis\The Sims\Sims Backup.exe' is denied.

**Comment by FaithBeam** [comment] 2020-04-02 17:54
@NER0888 
Try running the program as administrator.

**Comment by NER0888** [comment] 2020-04-03 11:35
> 
> 
> @NER0888
> Try running the program as administrator.

After running this patch as administrator i have this. 

![Annotation 2020-04-03 143308](https://user-images.githubusercontent.com/62935373/78356530-66f53680-75b8-11ea-86a3-58188608d194.png)

**Comment by NER0888** [comment] 2020-04-12 08:08
> 
> 
> @NER0888
> Try running the program as administrator.

After running this patch as administrator i have this. any idea why?

![Annotation 2020-04-03 143308](https://user-images.githubusercontent.com/62935373/78356530-66f53680-75b8-11ea-86a3-58188608d194.png)

**Comment by FaithBeam** [comment] 2020-05-11 22:41
@NER0888 It's been a while but I guess late is better than never. Please try this release which should solve that error. https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/1.2.3

The issue was that I was trying to delete that file but not checking if it existed in the first place. This release checks files and directories before deleting them.

**Closed** 2020-05-23 14:14 UTC
