### ISSUE TITLE
Having a black line on top of the UI

### ISSUE THREAD

**Issue by aikohime** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#49] opened 2022-05-07 23:51 UTC
**Installed Sims Version**
Sims 1 no expansions, Sims 1 Complete Collection, etc.
Sims 8 in 1

**Are you using a nocd exe / crack?**
Yes

**Describe the issue. Include screenshots if you can**
![Sims 2022-05-08 07-32-49-388](https://user-images.githubusercontent.com/105133595/167275501-aaf86875-76a8-4a45-9864-7a668d55c712.jpg)

**What are the steps to reproduce the issue?**
- use the patch (resolution 2560x1080 with DDrawCompat)
- enter the game (the neighborhood seems fine)
- go into the family and having a black line on top of the UI
- exit the game and try to patch with different resolution (1920x1080,2560x1440)and DgVoodoo2
- start the game mutiple times and doesn't fix the issue

**Please attach the generated log file SimsWidescreenPatcher.log**
[Sims1WidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/8646102/Sims1WidescreenPatcher.log)

**Comment by FaithBeam** [comment] 2022-05-08 12:14
@aikohime 
Hello! I see you are using 2.3.0 version of my patcher, can you try again with [2.3.1](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/2.3.1), please? I don't believe it will solve the issue of the black line, but it will fix that artifact in the middle of the panel.

Is this a Chinese locale install? I'm interested why the characters above the mood bars are going off the panel.

**Comment by FaithBeam** [comment] 2022-05-08 22:24
Was able to reproduce the issue.

![Sims_nfmzsP5aKQ](https://user-images.githubusercontent.com/32502411/167318226-92ad79af-fc25-4a8a-9ce8-0812e2732622.jpg)

**Comment by FaithBeam** [comment] 2022-05-08 22:31
This is what it's supposed to look like. I'm assuming I need to scale an image that is currently not.

![Sims_XIQ3jyD0YI](https://user-images.githubusercontent.com/32502411/167318403-c408f882-716e-49bd-9c84-6a1c8a38633c.jpg)

**Comment by FaithBeam** [comment] 2022-05-08 22:49
I think I found the image, UIGraphics\cpanel\Backgrounds\TallSubPanel.TGA.
![zopfli_TallSubPanel](https://user-images.githubusercontent.com/32502411/167319059-a5e8cf65-80bb-4126-93af-bab37f234c50.png)

It being tga is kind of annoying because I can't use my existing scaling methods.

**Comment by aikohime** [comment] 2022-05-08 22:55
It remains the same as I change to the latest version of the patcher v2.3.1. Maybe I should just wait for v2.3.2 instead.

**Comment by FaithBeam** [comment] 2022-05-17 20:24
@aikohime This will be fixed in the next release which will be a few days. Ignore the red squiggle, I was having fun :)
![ctsglcqM6E](https://user-images.githubusercontent.com/32502411/168903589-6ed7c378-ce5b-463d-830e-b9cc5f8fbec2.jpg)

**Comment by FaithBeam** [comment] 2022-05-18 20:23
@aikohime I created a new release that should fix this issue for you. https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/2.3.2

Let me know if that works.

**Closed** 2022-05-19 20:43 UTC
